Dev web/anp 82 admin charger adding
nmidzic20/WattsUp pull request #39
Opened 2023-12-16 19:16 UTC by kvardijan

Created a popup window that allows for admins to add charging stations to database. Implemented a map which can be used to pick a location of a new charging station. Station must be given a name, longitude and latitude. Map marker is located in the center of the map and can be moved by dragging the map (marker position refreshes on the end of the drag).

2023-12-16 21:15 UTC, FSostaric20 approved these changes

2023-12-17 12:50 UTC, ssmrcek20 requested changes
Function of adding stations works but design side should be fixed a little

2023-12-17 12:50 UTC, ssmrcek20 commented on web/src/app/add-station-dialogue/add-station-dialogue.component.scss
> +    height: 60vh;
Remove this width and height because it can look weird on some screens it's better to set size based on content.

2023-12-18 11:38 UTC, ssmrcek20 approved these changes
All good now!

2023-12-18 11:40 UTC, merged